next_books = [
	{"auteur": "Hume", "titre": "Enquête sur l'entendement humain", "mood":"curieuse"},
	{"auteur": "Maupassant", "titre":"Le Horla", "mood":"courageuse"},
	{"auteur": "La Boétie", "titre":"Discours sur la servitude volontaire", "mood":"curieuse"},
	{"auteur": "Paul Carrell", "titre":"Opération Barbarossa", "mood":"historienne"},
	{"auteur": "Giulio Bedeschi", "titre":"Cent mille gamelles de glace", "mood":"historienne"},
	{"auteur": "Grigori Baklanov", "titre":"Juillet 41", "mood":"historienne"},
	{"auteur": "Jules Verne", "titre":"Voyages et aventures du capitaine Hatteras", "mood":"aventurière"},
	{"auteur": "Arthur Conan Doyle", "titre":"Son dernier coup d'archet", "mood":"enquêtrice"},
	{"auteur": "Dostoievski", "titre":"Crime et châtiment", "mood":"classique"},
	{"auteur": "Ernest Cline", "titre":"Ready Player One", "mood":"courageuse"},
	{"auteur": "Umberto Eco", "titre":"Le nom de la rose", "mood":"classique"},
	{"auteur": "Nabokov", "titre":"Lolita", "mood":"coquine"},
	{"auteur": "Dickens", "titre":"David Copperfield", "mood":"classique"},
	{"auteur": "Gregory Bateson", "titre":"Vers une écologie de l'esprit", "mood":"curieuse"},
	{"auteur": "Edward Abbey", "titre":"Gang de la clef à molette", "mood":"curieuse"},
	{"auteur": "Henry David Thoreau", "titre":"La désobéissance civile", "mood":"rebelle"},
	{"auteur": "Edward Bernay", "titre":"Comment manipuler l'opinion en démocratie", "mood":"rebelle"},
	{"auteur": "Jankiel Wiernik", "titre":"Un an à Treblinka", "mood":"courageuse"},
	{"auteur": "Georges Orwell", "titre":"Dans la dèche à Paris et à Londres", "mood":"curieuse"},
	{"auteur": "Ken Kesey", "titre":"La machine à brouillard", "mood":"enquêtrice"},
	{"auteur": "Eldridge Cleaver", "titre":"Un noir à l'ombre", "mood":"rebelle"},
	{"auteur": "Razhig Keucheyan", "titre":"Les besoins artificiels", "mood":"rebelle"},
	{"auteur": "Gérard Mauger", "titre":"Repères pour résister à l'idéologie dominante", "mood":"rebelle"},
	{"auteur": "John Steinbeck", "titre":"A l'est d'Eden", "mood":"aventurière"},
	{"auteur": "Italo Calvino", "titre":"Le sentier des nids d'araignées", "mood":"bizarre"},
]